defaultPortal: customObjectsvHubDBSample
portals:
  - name: customObjectsvHubDBSample
    portalId: 9307273
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COrvtfT3LhIIAA0ADAAA4AEYiYm4BCCUgCIo7ukMMhkAz55HGavDIA1w2FS3bZJ7cyxWMl1i2fN-OiAAAARBAAAAeAAAAAAAAAAAgAEAAAAAAATAAMAHYP7_MUIZAM-eRxm6LZQz7KSRKAtwWmKKEUKqSDCnAg
        expiresAt: '2021-02-07T22:12:16.496Z'
    personalAccessKey: >-
      CiRmNTYwZGE2OC1lM2FlLTQxMGItYTE0Ny0zNmJjZjkzNTBhYTgQiYm4BBiUgCIqGQAF5pGCPdAhjYKV6x3reG70pnjx0p-_s3U
